site_name: A18 Wiki
theme:
  name: material
  language: it
  palette:
    scheme: default #chiaro, slate per scuro
    primary: indigo
    accent: indigo
   
nav:
 - Home: index.md
 - Conoscere la scuola:
    - Presentazione: scuola/presentazione.md
    - Gli organismi: scuola/organismi.md
    - Le figure: scuola/figure.md
    - I documenti: scuola/documenti.md
 - Filosofia:
    - Introduzione: filosofia/introduzione.md
    - Metodi: filosofia/metodi.md
 - Scienze Umane: scienze-umane.md
 - Risorse:
    - Libri: risorse/libri.md
    - Siti: risorse/siti.md
    
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences


extra_css:
  - styles/extra.css


